.TH "classification.h" 3 "Thu Jan 20 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
classification.h
.SH SYNOPSIS
.br
.PP
\fC#include <net/if\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqos_class\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__QOS_CLASSIFICATION_HAL_H__\fP"
.br
.ti -1c
.RI "#define \fBCLASS_MAC_SIZE\fP   18"
.br
.ti -1c
.RI "#define \fBCLASS_CHAIN_NAME_SIZE\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqos_addClass\fP (const struct \fBqos_class\fP *param)"
.br
.ti -1c
.RI "int \fBqos_removeAllClasses\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __QOS_CLASSIFICATION_HAL_H__"

.PP
Definition at line \fB22\fP of file \fBclassification\&.h\fP\&.
.SS "#define CLASS_CHAIN_NAME_SIZE   16"

.PP
Definition at line \fB28\fP of file \fBclassification\&.h\fP\&.
.SS "#define CLASS_MAC_SIZE   18"

.PP
Definition at line \fB27\fP of file \fBclassification\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int qos_addClass (const struct \fBqos_class\fP * param)"
API function checks the data in classification struct from \&.h file\&. Then build the dscp_mark iptables in that kind:
.PP
dmcli eRT addtable Device\&.QoS\&.Classification\&. dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.SourcePort int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.SourcePortRangeMax int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.DestPort int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.DestPortRangeMax int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.Protocol int -1
.PP
dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.TrafficClass int 2 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.ChainName string 'postrouting_qos'
.PP
dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.IfaceOut string 'erouter0' dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.DSCPMark int 32 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.SourceMACAddress string '00:e0:4c:81:c8:40' dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.IfaceIn string 'brlan0' dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.Enable bool true
.PP
The Parameter must be set
.PP
\fBParameters\fP
.RS 4
\fIparam\fP 
.RE
.PP
\fBReturns\fP
.RS 4
0 SUCCESS -1 FAIL 
.RE
.PP
Delete all classes before
.PP
Alloc space for command
.PP
Set iptables command in exec
.PP
Realloc space
.PP
Input exec into firewall and iptables
.PP
dealloc space
.PP
Integrate qos-firewall file into firewall
.PP
Definition at line \fB250\fP of file \fBclassification\&.c\fP\&.
.SS "int qos_removeAllClasses ()"

.PP
Definition at line \fB329\fP of file \fBclassification\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
