.TH "classification.c" 3 "Thu Jan 20 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
classification.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'classification\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqos_struct\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLASS_MASK_IPV4\fP   32"
.br
.ti -1c
.RI "#define \fBCLASS_MASK_IPV6\fP   128"
.br
.ti -1c
.RI "#define \fBCLASS_FW_FILENAME\fP   '/tmp/qos_rules\&.sh'"
.br
.ti -1c
.RI "#define \fBCLASS_FW_DEBUG\fP   '/home/tester/qos_rules\&.sh'"
.br
.ti -1c
.RI "#define \fBCLASS_FW_RELOAD_FILENAME\fP   '/etc/utopia/service\&.d/firewall_log_handle\&.sh'"
.br
.ti -1c
.RI "#define \fBCLASS_FW_RELOAD_DEBUG\fP   '/home/tester/firewall_log_handle\&.sh'"
.br
.ti -1c
.RI "#define \fBCLASS_IPTABLES_MANGLE_CMD\fP   'iptables \-t mangle'"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBclass_table\fP { \fBIPTABLES_IPV4\fP = (1 << 0), \fBIPTABLES_IPV6\fP = (1 << 1) }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBqos_struct\fP \fBinitQosClass\fP (const struct \fBqos_class\fP *class)"
.br
.ti -1c
.RI "int \fBdealloc_testclass\fP (\fBqos_struct\fP *class)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.ti -1c
.RI "int \fBqos_addClass\fP (const struct \fBqos_class\fP *param)"
.br
.ti -1c
.RI "int \fBqos_removeAllClasses\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLASS_FW_DEBUG   '/home/tester/qos_rules\&.sh'"

.PP
Definition at line \fB18\fP of file \fBclassification\&.c\fP\&.
.SS "#define CLASS_FW_FILENAME   '/tmp/qos_rules\&.sh'"

.PP
Definition at line \fB17\fP of file \fBclassification\&.c\fP\&.
.SS "#define CLASS_FW_RELOAD_DEBUG   '/home/tester/firewall_log_handle\&.sh'"

.PP
Definition at line \fB20\fP of file \fBclassification\&.c\fP\&.
.SS "#define CLASS_FW_RELOAD_FILENAME   '/etc/utopia/service\&.d/firewall_log_handle\&.sh'"

.PP
Definition at line \fB19\fP of file \fBclassification\&.c\fP\&.
.SS "#define CLASS_IPTABLES_MANGLE_CMD   'iptables \-t mangle'"

.PP
Definition at line \fB21\fP of file \fBclassification\&.c\fP\&.
.SS "#define CLASS_MASK_IPV4   32"

.PP
Definition at line \fB14\fP of file \fBclassification\&.c\fP\&.
.SS "#define CLASS_MASK_IPV6   128"

.PP
Definition at line \fB15\fP of file \fBclassification\&.c\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBclass_table\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIPTABLES_IPV4 \fP\fP
.TP
\fB\fIIPTABLES_IPV6 \fP\fP
.PP
Definition at line \fB23\fP of file \fBclassification\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int dealloc_testclass (\fBqos_struct\fP * class)"
Sets the space free of \fBqos_struct\fP 
.PP
\fBParameters\fP
.RS 4
\fIclass\fP 
.RE
.PP
\fBReturns\fP
.RS 4
0 SUCCESS -1 FAIL 
.RE
.PP

.PP
Definition at line \fB187\fP of file \fBclassification\&.c\fP\&.
.SS "\fBqos_struct\fP initQosClass (const struct \fBqos_class\fP * class)"
Allocates the data of \fBqos_class\fP 
.PP
\fBParameters\fP
.RS 4
\fIclass\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBqos_struct\fP of class 
.RE
.PP

.PP
Definition at line \fB171\fP of file \fBclassification\&.c\fP\&.
.SS "int main ()"
Test main func with a debug struct in main to add an set to add (pseudo) classification 
.PP
\fBReturns\fP
.RS 4
0 SUCCESS -1 FAIL 
.RE
.PP

.PP
Definition at line \fB200\fP of file \fBclassification\&.c\fP\&.
.SS "int qos_addClass (const struct \fBqos_class\fP * param)"
API function checks the data in classification struct from \&.h file\&. Then build the dscp_mark iptables in that kind:
.PP
dmcli eRT addtable Device\&.QoS\&.Classification\&. dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.SourcePort int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.SourcePortRangeMax int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.DestPort int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.DestPortRangeMax int -1 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.Protocol int -1
.PP
dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.TrafficClass int 2 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.ChainName string 'postrouting_qos'
.PP
dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.IfaceOut string 'erouter0' dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.DSCPMark int 32 dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.SourceMACAddress string '00:e0:4c:81:c8:40' dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.IfaceIn string 'brlan0' dmcli eRT setv Device\&.QoS\&.Classification\&.1\&.Enable bool true
.PP
The Parameter must be set
.PP
\fBParameters\fP
.RS 4
\fIparam\fP 
.RE
.PP
\fBReturns\fP
.RS 4
0 SUCCESS -1 FAIL 
.RE
.PP
Delete all classes before
.PP
Alloc space for command
.PP
Set iptables command in exec
.PP
Realloc space
.PP
Input exec into firewall and iptables
.PP
dealloc space
.PP
Integrate qos-firewall file into firewall
.PP
Definition at line \fB250\fP of file \fBclassification\&.c\fP\&.
.SS "int qos_removeAllClasses ()"

.PP
Definition at line \fB329\fP of file \fBclassification\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
