.TH "md__r_e_a_d_m_e" 3 "Thu Jan 20 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- hal_qos 
Use 'cake' instead of htb prioritiy and class
.PP
tc qdisc add dev erouter0 root cake bandwidth 25Mbit overhead 0 mpu 0 diffserv4
.PP
parameters:
.IP "\(bu" 2
interface: erouter0 
.br

.IP "\(bu" 2
bandwith: <N> 
.br

.PP
.PP
configuration with dmcli
.PP
dmcli eRT addtable Device\&.QoS\&.Queue\&. 
.br
 dmcli eRT setv Device\&.QoS\&.Queue\&.1\&.Interface string 'erouter0' 
.br
 dmcli eRT setv Device\&.QoS\&.Queue\&.1\&.ShapingRate int 25 
.br
 dmcli eRT setv Device\&.QoS\&.Queue\&.1\&.Enable bool true 
.br
.PP
This is simple code without any error procedures etc\&. 
