.TH "qos_class" 3 "Thu Jan 20 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qos_class
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <classification\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBid\fP"
.br
.ti -1c
.RI "int \fBtraffic_class\fP"
.br
.ti -1c
.RI "char \fBchain_name\fP [\fBCLASS_CHAIN_NAME_SIZE\fP]"
.br
.ti -1c
.RI "int \fBdscp_mark\fP"
.br
.ti -1c
.RI "char \fBiface_in\fP [IFNAMSIZ]"
.br
.ti -1c
.RI "char \fBiface_out\fP [IFNAMSIZ]"
.br
.ti -1c
.RI "char \fBip_src_addr\fP [INET6_ADDRSTRLEN]"
.br
.ti -1c
.RI "int \fBip_src_mask\fP"
.br
.ti -1c
.RI "char \fBip_dst_addr\fP [INET6_ADDRSTRLEN]"
.br
.ti -1c
.RI "int \fBip_dst_mask\fP"
.br
.ti -1c
.RI "int \fBprotocol\fP"
.br
.ti -1c
.RI "int \fBport_src_range_start\fP"
.br
.ti -1c
.RI "int \fBport_src_range_end\fP"
.br
.ti -1c
.RI "int \fBport_dst_range_start\fP"
.br
.ti -1c
.RI "int \fBport_dst_range_end\fP"
.br
.ti -1c
.RI "char \fBmac_src_addr\fP [\fBCLASS_MAC_SIZE\fP]"
.br
.ti -1c
.RI "int \fBtcp_flags\fP"
.br
.ti -1c
.RI "int \fBtcp_psh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBclassification\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char chain_name[\fBCLASS_CHAIN_NAME_SIZE\fP]"

.PP
Definition at line \fB37\fP of file \fBclassification\&.h\fP\&.
.SS "int dscp_mark"

.PP
Definition at line \fB39\fP of file \fBclassification\&.h\fP\&.
.SS "unsigned id"

.PP
Definition at line \fB33\fP of file \fBclassification\&.h\fP\&.
.SS "char iface_in[IFNAMSIZ]"

.PP
Definition at line \fB41\fP of file \fBclassification\&.h\fP\&.
.SS "char iface_out[IFNAMSIZ]"

.PP
Definition at line \fB43\fP of file \fBclassification\&.h\fP\&.
.SS "char ip_dst_addr[INET6_ADDRSTRLEN]"

.PP
Definition at line \fB49\fP of file \fBclassification\&.h\fP\&.
.SS "int ip_dst_mask"

.PP
Definition at line \fB51\fP of file \fBclassification\&.h\fP\&.
.SS "char ip_src_addr[INET6_ADDRSTRLEN]"

.PP
Definition at line \fB45\fP of file \fBclassification\&.h\fP\&.
.SS "int ip_src_mask"

.PP
Definition at line \fB47\fP of file \fBclassification\&.h\fP\&.
.SS "char mac_src_addr[\fBCLASS_MAC_SIZE\fP]"

.PP
Definition at line \fB63\fP of file \fBclassification\&.h\fP\&.
.SS "int port_dst_range_end"

.PP
Definition at line \fB61\fP of file \fBclassification\&.h\fP\&.
.SS "int port_dst_range_start"

.PP
Definition at line \fB59\fP of file \fBclassification\&.h\fP\&.
.SS "int port_src_range_end"

.PP
Definition at line \fB57\fP of file \fBclassification\&.h\fP\&.
.SS "int port_src_range_start"

.PP
Definition at line \fB55\fP of file \fBclassification\&.h\fP\&.
.SS "int protocol"

.PP
Definition at line \fB53\fP of file \fBclassification\&.h\fP\&.
.SS "int tcp_flags"

.PP
Definition at line \fB65\fP of file \fBclassification\&.h\fP\&.
.SS "int tcp_psh"

.PP
Definition at line \fB67\fP of file \fBclassification\&.h\fP\&.
.SS "int traffic_class"

.PP
Definition at line \fB35\fP of file \fBclassification\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
