.TH "qos_struct" 3 "Thu Jan 20 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qos_struct
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const struct \fBqos_class\fP * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Type to alloc the qos class in an type 
.PP
Definition at line \fB160\fP of file \fBclassification\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "const struct \fBqos_class\fP* data"

.PP
Definition at line \fB162\fP of file \fBclassification\&.c\fP\&.
.SS "size_t size"

.PP
Definition at line \fB163\fP of file \fBclassification\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
