.TH "queue.h" 3 "Thu Jan 20 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue.h
.SH SYNOPSIS
.br
.PP
\fC#include <net/if\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBqos_queue\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUEUE_MAX_TC\fP   16"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBqueue_alg\fP { \fBQUEUE_ALG_SP\fP, \fBQUEUE_ALG_WRR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqos_addQueue\fP (int index, struct \fBqos_queue\fP *queue)"
.br
.ti -1c
.RI "int \fBqos_removeQueue\fP (struct \fBqos_queue\fP *queue)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QUEUE_MAX_TC   16"

.PP
Definition at line \fB25\fP of file \fBqueue\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBqueue_alg\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIQUEUE_ALG_SP \fP\fP
.TP
\fB\fIQUEUE_ALG_WRR \fP\fP
.PP
Definition at line \fB27\fP of file \fBqueue\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int qos_addQueue (int index, struct \fBqos_queue\fP * queue)"

.PP
Definition at line \fB60\fP of file \fBqueue\&.c\fP\&.
.SS "int qos_removeQueue (struct \fBqos_queue\fP * queue)"

.PP
Definition at line \fB35\fP of file \fBqueue\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
